/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as BatchtrakRouteImport } from './routes/batchtrak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'

const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchtrakRoute = BatchtrakRouteImport.update({
  id: '/batchtrak',
  path: '/batchtrak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batchtrak': typeof BatchtrakRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batchtrak': typeof BatchtrakRoute
  '/recipes': typeof RecipesRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batchtrak': typeof BatchtrakRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batchtrak' | '/inventory' | '/recipes' | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batchtrak' | '/recipes' | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/batchtrak'
    | '/inventory'
    | '/recipes'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchtrakRoute: typeof BatchtrakRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  RecipesRoute: typeof RecipesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batchtrak': {
      id: '/batchtrak'
      path: '/batchtrak'
      fullPath: '/batchtrak'
      preLoaderRoute: typeof BatchtrakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchtrakRoute: BatchtrakRoute,
  InventoryRoute: InventoryRouteWithChildren,
  RecipesRoute: RecipesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
